CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL
);


CREATE TABLE orders (
  id INT PRIMARY KEY AUTO_INCREMENT,
  uid INT NOT NULL
);

CREATE TABLE payments (
  id INT PRIMARY KEY AUTO_INCREMENT,
  oid INT NOT NULL,
  uid INT NOT NULL
);

CREATE TABLE refundorders (
  id INT PRIMARY KEY AUTO_INCREMENT,
  uid INT NOT NULL
);

CREATE TABLE refunds (
  id INT PRIMARY KEY AUTO_INCREMENT,
  uid INT NOT NULL,
  roid INT NOT NULL
);

